import type { Metadata } from "next";
import { ProgressBarProviders } from "./providers/progress-bar-providers";
import "@/styles/globals.css";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ProgressBarProviders>{children}</ProgressBarProviders>
      </body>
    </html>
  );
}
