import type { Metadata } from "next";
import { ProgressBarProviders } from "./providers/progress-bar-providers";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import "@/styles/globals.scss";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const local = await getLocale();
  const messages = await getMessages();
  return (
    <html lang={local}>
      <body>
        <NextIntlClientProvider messages={messages}>
          <ProgressBarProviders>{children}</ProgressBarProviders>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
